global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # qBTC node monitoring
  - job_name: 'qbtc-node'
    metrics_path: '/health'
    static_configs:
      - targets: ['qbtc-node:8080']

  # Redis monitoring (if enabled)
  - job_name: 'redis'
    static_configs:
      - targets: ['qbtc-redis:6379']